version: '2.2'
services:
  backend:
    container_name: docker2 #container name
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/app #Maps our local dir "." to /app in docker
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    environment:
      - DEBUG=1
    depends_on:
      - db  


  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: root 
      POSTGRES_PASSWORD: root  
      POSTGRES_ROOT_PASSWORD: admin
    ports:
      - "5430:5432"
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "5050:80"

    